# MongoDB
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

# JWT
localcab.security.jwt.secret=${JWT_SECRET}
localcab.security.jwt.expiration-ms=86400000

# Admin
localcab.admin.username=${ADMIN_USERNAME}
localcab.admin.password=${ADMIN_PASSWORD}

spring.security.filter.dispatcher-types=REQUEST,ERROR

# Groq
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.options.model=llama3-8b-8192

# Razorpay
razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}
razorpay.currency=${RAZORPAY_CURRENCY:INR}